# Generated by Django 4.2.7 on 2023-12-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tampus_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
