# Generated by Django 4.2.7 on 2023-12-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tampus_admin', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User_admin',
        ),
    ]
