# Generated by Django 4.0.1 on 2023-12-11 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tampus_api', '0002_alter_anuncio_table_alter_anuncio_etiqueta_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioEtiqueta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('estado_favorito', models.BooleanField()),
                ('fecha_creacion', models.DateField(null=True)),
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='anuncio_etiqueta',
            name='id_anuncio',
        ),
        migrations.RemoveField(
            model_name='anuncio_etiqueta',
            name='id_etiqueta',
        ),
        migrations.RemoveField(
            model_name='anuncio_imagen',
            name='id_anuncio',
        ),
        migrations.RemoveField(
            model_name='anuncio_imagen',
            name='id_imagen',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='id_institucion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='perfil_imagen',
            name='id_imagen',
        ),
        migrations.RemoveField(
            model_name='perfil_imagen',
            name='id_perfil',
        ),
        migrations.RemoveConstraint(
            model_name='anuncio',
            name='check_precio_max',
        ),
        migrations.RemoveConstraint(
            model_name='anuncio',
            name='check_precio_positivo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='token',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='apellido_usuario',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='dimensiones',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='estado_anuncio',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='id_anuncio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tampus_api.usuarios'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='precio_max',
            field=models.DecimalField(decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='precio_min',
            field=models.DecimalField(decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='proposito',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo_espacio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='id_etiqueta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='created_by',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado_user',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(blank=True, choices=[('ROLE_ANFITRION', 'Anfitrión'), ('ROLE_ESTUDIANTE', 'Estudiante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='updated_by',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterModelTable(
            name='anuncio',
            table=None,
        ),
        migrations.AlterModelTable(
            name='etiqueta',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
        migrations.DeleteModel(
            name='Anuncio_Etiqueta',
        ),
        migrations.DeleteModel(
            name='Anuncio_Imagen',
        ),
        migrations.DeleteModel(
            name='Imagenes',
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Perfil_Imagen',
        ),
        migrations.AddField(
            model_name='favoritos',
            name='id_anuncio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tampus_api.anuncio'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tampus_api.usuarios'),
        ),
        migrations.AddField(
            model_name='anuncioetiqueta',
            name='id_anuncio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tampus_api.anuncio'),
        ),
        migrations.AddField(
            model_name='anuncioetiqueta',
            name='id_etiqueta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tampus_api.etiqueta'),
        ),
    ]
